notes_project/asterisk_app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', client_list, name='client_list'),
    path('<int:pk>/', client_detail, name='client_detail'),

    path('add/', add_client, name='add_client'),
    path('<int:pk>/edit/', edit_client, name='edit_client'),
    path('<int:pk>/delete/', delete_client, name='delete_client'),

    path('api/asterisk_status/', asterisk_status, name='asterisk_status'),
    path('calls/', call_list, name='call_list'),
]

notes_project/notes_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_page, name='home'),  # Главная страница
    path('notes/', views.NoteListView.as_view(), name='note_list'),  # all notes
    path('note/<int:pk>/', views.NoteDetailView.as_view(), name='note_detail'),
    path('note/new/', views.NoteCreateView.as_view(), name='note_create'),  # Добавление заметки
    path('note/<int:pk>/edit/', views.NoteUpdateView.as_view(), name='note_edit'),  # Редактирование заметки
    path('note/<int:pk>/delete/', views.NoteDeleteView.as_view(), name='note_delete'),  # Удаление заметки
]

notes_project/notes_project/urls.py
#notes_project/urls.py

"""
URL configuration for notes_project project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes_app.urls')), # Подключаем маршруты notes_app
    path('clients/', include('asterisk_app.urls')), # Подключаем маршруты asterisk_app
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes_project/asterisk_app/models.py
#asterisk_app/models

from django.db import models
from django.utils import timezone
from django.urls import reverse
from cloudinary.models import CloudinaryField

class ContactInfo(models.Model):
    phone = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(unique=True, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"Phone: {self.phone}, Email: {self.email}"

class Client(models.Model):
    name = models.CharField(max_length=55)
    contact_info = models.OneToOneField(ContactInfo, on_delete=models.CASCADE, null=True, blank=True)
    image = CloudinaryField('image', blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ClientCard(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    is_primary = models.BooleanField(default=False)  # Primary card
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Card for {self.client.name}'

class CallRecord(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True, blank=True)
    channel = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    state = models.CharField(max_length=50, choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')])
    application_data = models.TextField()
    calling_number = models.CharField(max_length=50)
    client_image = models.ImageField(upload_to='client_images/', blank=True, null=True)
    duration = models.PositiveIntegerField(null=True, blank=True)  # Duration in seconds
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.channel} - {self.state}"

notes_project/asterisk_app/forms.py
from django import forms
from .models import *

from django import forms
from .models import Client, ContactInfo

class ContactInfoForm(forms.ModelForm):
    class Meta:
        model = ContactInfo
        fields = ['phone', 'email', 'address']

class ClientForm(forms.ModelForm):
    contact_info_phone = forms.CharField(max_length=20, required=False,  widget=forms.TextInput(attrs={'placeholder': 'Enter your phone number'}))
    contact_info_email = forms.EmailField(required=False)
    contact_info_address = forms.CharField(max_length=255, required=False)

    class Meta:
        model = Client
        fields = ['name', 'image', 'is_active']

    def save(self, commit=True):
        instance = super().save(commit=False)

        contact_info_data = {
            'phone': self.cleaned_data['contact_info_phone'],
            'email': self.cleaned_data['contact_info_email'],
            'address': self.cleaned_data['contact_info_address']
        }

        # Create or update the ContactInfo instance
        contact_info, created = ContactInfo.objects.get_or_create(
            phone=contact_info_data['phone'],
            email=contact_info_data['email'],
            address=contact_info_data['address']
        )
        instance.contact_info = contact_info

        if commit:
            instance.save()

        return instance

notes_project/asterisk_app/views.py
import os
from dotenv import load_dotenv
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
import threading
import time
from .models import *
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .forms import ClientForm
from .scripts.asterisk_connection import AsteriskConnection
from .scripts.calling_number import calling_number

# Глобальная переменная для хранения статуса


host = os.getenv('ASTERISK_HOST')  # IP-адрес сервера
port = int(os.getenv('ASTERISK_PORT', 22))  # Преобразуем порт в число
username = os.getenv('ASTERISK_USERNAME')  # Имя пользователя для подключения
password = os.getenv('ASTERISK_PASSWORD')  # Пароль для подключения
load_dotenv()



def asterisk_status(request):
    asterisk_conn = AsteriskConnection(host, port, username, password)
    asterisk_conn.connect()

    status = asterisk_conn.check_connection()
    if status:
        active_calls = asterisk_conn.get_active_calls()
        calling_numbers = calling_number.get_active_calls().get('calling_numbers', [])

    else:
        active_calls = "no asterisk connection"
        calling_numbers = []

    # Дополнительно получаем клиентов, чьи номера совпадают с номерами звонящих
    clients = Client.objects.all()
    client_names = []

    for client in clients:
         # Сопоставляем номера клиентов с их именами
        if client.contact_info and client.contact_info.phone:
            for number in calling_numbers:
                if number == client.contact_info.phone:
                    client_names.append(client.name)

    # Возвращаем JSON с добавленным именем клиента, если номер совпал
    return JsonResponse({
        'asterisk_status': status,
        'active_calls': active_calls,
        'calling_numbers': calling_numbers,
        'client_names': client_names  # Добавляем пары "номер звонящего": "имя клиента"
    })





def client_list(request):
    #clients = Client.objects.all().values('id', 'name', 'is_active')
    clients = Client.objects.all()
    context = {
        'clients': clients,
    }
    #return JsonResponse(list(clients), safe=False)
    return render(request, 'asterisk_app/client_list.html', context)


def client_detail(request, pk):

    clients = Client.objects.all()
    client = get_object_or_404(Client, pk=pk)
    context = {

        'clients': clients,
        'client': client,
    }
    return render(request, 'asterisk_app/client_detail.html', context)

# Страница добавления клиента
def add_client(request):
    clients = Client.objects.all()
    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('client_list')
    else:
        form = ClientForm()

    context = {
        'form': form,
        'clients': clients,
    }
    return render(request, 'asterisk_app/add_client.html', context)


def edit_client(request, pk):

    clients = Client.objects.all()
    client = get_object_or_404(Client, pk=pk)
    if request.method == "POST":
        form = ClientForm(request.POST, request.FILES, instance=client)
        if form.is_valid():
            form.save()
            return redirect('client_list')
    else:
        form=ClientForm(instance=client)
    context = {
        'form': form,

        'clients': clients,
        'client': client,
    }
    return render(request, 'asterisk_app/add_client.html', context)

def delete_client(request, pk):
    clients = Client.objects.all()
    client = get_object_or_404(Client, pk=pk)
    if request.method == "POST":
        client_name = client.name
        client.delete()  # Удаляем клиента
        messages.success(request, f"Клиент {client_name} был успешно удален")
        # messages.success(request, f"Client {client.name} successfully deleted.")
        return redirect('client_list')  # Перенаправляем на список клиентов
    context = {
        'clients': clients,
        'client': client,
    }
    return render(request, 'asterisk_app/delete_client.html', context)


def call_list(request):
    calls = CallRecord.objects.all()
    context = {
        'calls': calls,
    }
    return render(request, 'asterisk_app/call_list.html', context)

notes_project/templates/asterisk_app/add_client.html
{% extends 'base.html' %}

{% block title %}Add New Client{% endblock %}

{% block content %}
<h1>Add New Client</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div>
        <label for="id_name">Name</label>
        <input type="text" name="name" id="id_name" value="{{ form.name.value }}">
    </div>

    <div>
        <label for="id_image">Image</label>
        <input type="file" name="image" id="id_image">
    </div>

    <div>
        <label for="id_is_active">Active</label>
        <input type="checkbox" name="is_active" id="id_is_active" {% if form.is_active.value %}checked{% endif %}>
    </div>

   <div>
        <label for="id_contact_info_phone">Phone</label>
        <input type="text" name="contact_info_phone" id="id_contact_info_phone" placeholder="Enter your phone number" value="{{ form.contact_info_phone.value }}">
    </div>

    <div>
        <label for="id_contact_info_email">Email</label>
        <input type="email" name="contact_info_email" id="id_contact_info_email" value="{{ form.contact_info_email.value }}">
    </div>

    <div>
        <label for="id_contact_info_address">Address</label>
        <input type="text" name="contact_info_address" id="id_contact_info_address" value="{{ form.contact_info_address.value }}">
    </div>

    <button type="submit">Add Client</button>
</form>
<br>
<a href="{% url 'client_list' %}">Back to Client List</a>
{% endblock %}

notes_project/templates/asterisk_app/asterisk_con.html
{% extends 'base.html' %}

{% block content %}
    <h2>Статус подключения к Asterisk</h2>
    {% if is_connected %}
        <p>Подключение к серверу Asterisk успешно!</p>
    {% else %}
        <p>Не удалось подключиться к серверу Asterisk.</p>
    {% endif %}
{% endblock %}

notes_project/templates/asterisk_app/call_list.html
<!-- templates/asterisk_app/call_list.html -->
{% extends 'base.html' %}

{% block content %}
  <h1>Журнал звонков</h1>
  <ul>
    {% for call in calls %}
        <li>{{ call.calling_number }} - {{ call.state }} ({{ call.created_at }})</li>
    {% empty %}
        <p>Звонков пока нет.</p>
    {% endfor %}
</ul>

{% block extra_js %}
<script>
    console.log("Этот скрипт только для определенной страницы");
</script>
{% endblock %}
{% endblock %}

notes_project/templates/asterisk_app/client_detail.html
<!-- templates/asterisk_app/client_detail.html -->
{% extends 'base.html' %}

{% block content %}
  <h1>{{ client.name }}</h1>

<p><strong>Email:</strong> {{ client.contact_info.email }}</p>
  <p>Email: {{ client.contact_info }}</p>
<p>Телефон: {{ client.contact_info.phone }}</p>

{% if client.image %}
    <img src="{{ client.image.url }}" alt="{{ client.name }}">
{% endif %}
 <a href="{% url 'edit_client' pk=client.pk %}">Редактировать</a>

  <br>
  <a href="{% url 'client_list' %}">Вернуться к списку клиентов</a>
{% endblock %}

notes_project/templates/asterisk_app/client_form.html
<!-- templates/asterisk_app/client_form.html -->
{% extends 'base.html' %}

{% block title %}{% if client %}Редактировать клиента{% else %}Создать клиента{% endif %}{% endblock %}

{% block content %}
    <h2>{% if client %}Редактировать клиента{% else %}Создать нового клиента{% endif %}</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Отображение формы -->

        <button type="submit">{% if client %}Сохранить изменения{% else %}Создать клиента{% endif %}</button>
    </form>

    <a href="{% url 'client_list' %}">Назад к списку клиентов</a>
{% endblock %}

notes_project/templates/asterisk_app/client_list.html
<!-- templates/asterisk_app/clients_list.html -->
{% extends 'base.html' %}

{% block title %}Список клиентов{% endblock %}

{% block content %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

    <h1>All Clients</h1>
  <!-- Статус соединения с Asterisk -->

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Image</th>
            <th>Actions</th>
        </tr>
    </thead>



    <tbody>
        {% for client in clients %}
        <tr>
            <td><a href="{% url 'client_detail' client.pk %}" target="_blank">{{ client.name }}</a></td>
            <td>{{ client.contact_info.phone }}</td>
            <td>{{ client.contact_info.email }}</td>

            <td>
                {% if client.image %}
                    <img src="{{ client.image.url }}" alt="{{ client.name }}" width="50" height="50" class="thumbnail" onclick="openImageModal('{{ client.image.url }}')">
                {% else %}
                    No image
                {% endif %}
            </td>
            <td>
                <a href="{% url 'edit_client' client.pk %}">Edit</a> /
                <a href="{% url 'delete_client' client.pk %}">Delete</a>
            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>

<br>
<a href="{% url 'add_client' %}">Add New Client</a>


{% endblock %}

notes_project/templates/asterisk_app/delete_client.html
{% extends 'base.html' %}

{% block title %}Delete Client{% endblock %}

{% block content %}
<h1>Delete Client</h1>
<p>Are you sure you want to delete the client <strong>{{ client.name }}</strong>?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, Delete</button>
</form>

<br>
<a href="{% url 'client_list' %}">Cancel</a>
{% endblock %}

notes_project/templates/asterisk_app/edit_client.html
{% extends 'base.html' %}

{% block title %}Edit Client{% endblock %}

{% block content %}
<h1>Edit Client</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Client</button>
     <a href="{% url 'client_list' %}">Cancel</a>
</form>
<br>
<a href="{% url 'client_list' %}">Back to Client List</a>
{% endblock %}